dist: xenial
language: generic

env:
  matrix:
    - AMCL_LANG=cpp
    - AMCL_LANG=java
    - AMCL_LANG=js
    - AMCL_LANG=rust
    - AMCL_LANG=swift
    - AMCL_LANG=wasm-c
    - AMCL_LANG=wasm-rust

script:
  - ./scripts/travis.sh

notifications:
  email: false
